export const setActiveTab = 'SET_ACTIVE_TAB';
export const SET_FILTER = 'SET_FILTER';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_SEARCHID_SUCCESS = 'FETCH_SEARCHID_SUCCESS';
